### ISSUE TITLE
Any Plan of Command Line wake up like this?

### ISSUE THREAD

**Issue by shenmo7192** [deepin-espanol/WebApp#3]
We've made a very similar project like this with Qt5
The Spark Web Core
https://dcstore.spark-app.store/store/tools/spark-web-core/spark-web-core_1.0.1_all.deb
We use it like this
https://dcstore.spark-app.store/store/others/gaster-translator/gaster-translator_1.0.0_all.deb
spark-web-core {title} {url} 1024 768

**Comment by alvarosamudio** [comment]
thank you very much for your support
