### ISSUE TITLE
Donwload file bug

### ISSUE THREAD

**Issue by ghost** [deepin-espanol/WebApp#6]
Hi. I have problem with this bug. I can not file download with chat application by website. It needs to open a tab or windows browser to download files.
I hope you guys find a way to fix it.
Thank for share.

**Comment by shenmo7192** [comment]
[https://gitee.com/deepin-community-store/spark-web-app-runtime](https://gitee.com/deepin-community-store/spark-web-app-runtime)
you can try this

**Comment by ghost** [comment]
> https://gitee.com/deepin-community-store/spark-web-app-runtime
> you can try this

Thank you. Thank for you so much, i have solved the problem.
